### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0 so that keras will be wrapped up with the tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr) # for index representation

[[9595, 1608, 5064, 325], [9595, 1608, 5064, 7068], [9595, 9151, 5064, 7813], [6634, 3458, 6, 8911, 1519], [6634, 3458, 6, 8911, 3608], [8094, 9595, 9424, 5064, 4888], [516, 668, 5078, 8911]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8 # based on your sentence length
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # pre add 0's in front to make sentences complete for 8 word sentence
print(embedded_docs) # for formatting index matrix

[[   0    0    0    0 9595 1608 5064  325]
 [   0    0    0    0 9595 1608 5064 7068]
 [   0    0    0    0 9595 9151 5064 7813]
 [   0    0    0 6634 3458    6 8911 1519]
 [   0    0    0 6634 3458    6 8911 3608]
 [   0    0    0 8094 9595 9424 5064 4888]
 [   0    0    0    0  516  668 5078 8911]]


In [11]:
dim=10 # 10 feature representation

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 121ms/step
[[[ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508
   -0.03607981 -0.03785805  0.02148269  0.00705695  0.00344991]
  [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508
   -0.03607981 -0.03785805  0.02148269  0.00705695  0.00344991]
  [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508
   -0.03607981 -0.03785805  0.02148269  0.00705695  0.00344991]
  [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508
   -0.03607981 -0.03785805  0.02148269  0.00705695  0.00344991]
  [ 0.0075762  -0.03155445  0.0318601  -0.0391659   0.00947879
    0.04974449  0.04078056  0.00260438  0.02187785 -0.02125386]
  [ 0.01586683  0.03119406 -0.04957014  0.0389375   0.00372257
   -0.03997375  0.03753528 -0.030378   -0.02999703  0.02409798]
  [ 0.04432025 -0.04237002 -0.01713753  0.03976745 -0.01140196
    0.02180251  0.03776219  0.04292205  0.01006383 -0.04266175]
  [-0.02603967 -0.01964387 -0.00212934 -0.04024942  0.0312

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9595, 1608, 5064,  325], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0]) # 0th word index of sentence converted in form of 10 vectors

1/1 [==============================] - 0s 24ms/step
[[ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508 -0.03607981
  -0.03785805  0.02148269  0.00705695  0.00344991]
 [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508 -0.03607981
  -0.03785805  0.02148269  0.00705695  0.00344991]
 [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508 -0.03607981
  -0.03785805  0.02148269  0.00705695  0.00344991]
 [ 0.03686259 -0.04046825 -0.03742952 -0.00241417 -0.00026508 -0.03607981
  -0.03785805  0.02148269  0.00705695  0.00344991]
 [ 0.0075762  -0.03155445  0.0318601  -0.0391659   0.00947879  0.04974449
   0.04078056  0.00260438  0.02187785 -0.02125386]
 [ 0.01586683  0.03119406 -0.04957014  0.0389375   0.00372257 -0.03997375
   0.03753528 -0.030378   -0.02999703  0.02409798]
 [ 0.04432025 -0.04237002 -0.01713753  0.03976745 -0.01140196  0.02180251
   0.03776219  0.04292205  0.01006383 -0.04266175]
 [-0.02603967 -0.01964387 -0.00212934 -0.04024942  0.03121611  0.00744843